name: Cross compile for ARM64

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install cross compiler and build utils
        run: |
          apt-get update
          apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu cmake build-essential

      - name: Cross compile
      	id: cross_compile
        run: |
          mkdir build
          cd build
          cmake ..
          make -j4 package
          echo "::set-output name=ARM64_DEB_PACKAGE::$(basename $(find . -maxdepth 1 -name *.deb))"

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.cross_compile.outputs.ARM64_DEB_PACKAGE }}
          path: ${{ github.workspace }}/build/${{ steps.cross_compile.outputs.ARM64_DEB_PACKAGE }}
